export type LocationType =
  | "city"
  | "market-town"
  | "town"
  | "suburb"
  | "village"
  | "region";

export interface Location {
  slug: string;
  lat: number;
  lng: number;
  postcode: string;
  type: LocationType;
  region: string;
}

export const LOCATIONS: Location[] = [
  { slug: "york", lat: 53.959, lng: -1.082, postcode: "YO1", type: "city", region: "North Yorkshire" },
  { slug: "selby", lat: 53.781, lng: -1.070, postcode: "YO8", type: "town", region: "North Yorkshire" },
  { slug: "tadcaster", lat: 53.885, lng: -1.264, postcode: "LS24", type: "town", region: "North Yorkshire" },
  { slug: "pocklington", lat: 53.930, lng: -0.780, postcode: "YO42", type: "market-town", region: "East Riding of Yorkshire" },
  { slug: "elvington", lat: 53.917, lng: -0.948, postcode: "YO41", type: "village", region: "North Yorkshire" },
  { slug: "welburn", lat: 54.111, lng: -0.864, postcode: "YO60", type: "village", region: "North Yorkshire" },
  { slug: "stamford-bridge", lat: 54.017, lng: -0.909, postcode: "YO41", type: "village", region: "East Riding of Yorkshire" },
  { slug: "towton", lat: 53.847, lng: -1.277, postcode: "LS24", type: "village", region: "North Yorkshire" },
  { slug: "wetherby", lat: 53.928, lng: -1.386, postcode: "LS22", type: "town", region: "West Yorkshire" },
  { slug: "harrogate", lat: 53.992, lng: -1.541, postcode: "HG1", type: "town", region: "North Yorkshire" },
  { slug: "knaresborough", lat: 54.009, lng: -1.465, postcode: "HG5", type: "market-town", region: "North Yorkshire" },
  { slug: "ripley", lat: 54.039, lng: -1.537, postcode: "HG3", type: "village", region: "North Yorkshire" },
  { slug: "spofforth", lat: 53.978, lng: -1.470, postcode: "HG3", type: "village", region: "North Yorkshire" },
  { slug: "follifoot", lat: 53.970, lng: -1.493, postcode: "HG3", type: "village", region: "North Yorkshire" },
  { slug: "pannal", lat: 53.964, lng: -1.537, postcode: "HG3", type: "village", region: "North Yorkshire" },
  { slug: "beckwithshaw", lat: 53.964, lng: -1.537, postcode: "HG3", type: "village", region: "North Yorkshire" },
  { slug: "darely", lat: 53.964, lng: -1.537, postcode: "HG3", type: "village", region: "North Yorkshire" },
  { slug: "starbeck", lat: 53.964, lng: -1.537, postcode: "HG1", type: "suburb", region: "North Yorkshire" },
  { slug: "leeds", lat: 53.800, lng: -1.549, postcode: "LS1", type: "city", region: "West Yorkshire" },
  { slug: "garforth", lat: 53.791, lng: -1.381, postcode: "LS25", type: "suburb", region: "West Yorkshire" },
  { slug: "rothwell", lat: 53.752, lng: -1.478, postcode: "LS26", type: "suburb", region: "West Yorkshire" },
  { slug: "horsforth", lat: 53.843, lng: -1.637, postcode: "LS18", type: "suburb", region: "West Yorkshire" },
  { slug: "otley", lat: 53.905, lng: -1.691, postcode: "LS21", type: "market-town", region: "West Yorkshire" },
  { slug: "ripon", lat: 54.137, lng: -1.521, postcode: "HG4", type: "city", region: "North Yorkshire" },
  { slug: "thirsk", lat: 54.232, lng: -1.343, postcode: "YO7", type: "market-town", region: "North Yorkshire" },
  { slug: "masham", lat: 54.222, lng: -1.656, postcode: "HG4", type: "market-town", region: "North Yorkshire" },
  { slug: "boroughbridge", lat: 54.095, lng: -1.399, postcode: "YO51", type: "market-town", region: "North Yorkshire" },
  { slug: "easingwold", lat: 54.120, lng: -1.190, postcode: "YO61", type: "market-town", region: "North Yorkshire" },
  { slug: "helmsley", lat: 54.245, lng: -1.056, postcode: "YO62", type: "market-town", region: "North Yorkshire" },
  { slug: "pickering", lat: 54.243, lng: -0.777, postcode: "YO18", type: "market-town", region: "North Yorkshire" },
  { slug: "sherburn-in-elmet", lat: 53.768, lng: -1.232, postcode: "LS25", type: "village", region: "North Yorkshire" },
  { slug: "cawood", lat: 53.833, lng: -1.127, postcode: "YO8", type: "village", region: "North Yorkshire" },
  { slug: "riccall", lat: 53.833, lng: -1.127, postcode: "YO19", type: "village", region: "North Yorkshire" },
  { slug: "bishopthorpe", lat: 53.920, lng: -1.099, postcode: "YO23", type: "village", region: "North Yorkshire" },
  { slug: "copmanthorpe", lat: 53.920, lng: -1.099, postcode: "YO23", type: "village", region: "North Yorkshire" },
  { slug: "haxby", lat: 53.990, lng: -1.072, postcode: "YO32", type: "suburb", region: "North Yorkshire" },
  { slug: "strensall", lat: 53.990, lng: -1.072, postcode: "YO32", type: "village", region: "North Yorkshire" },
  { slug: "huntington", lat: 53.990, lng: -1.072, postcode: "YO32", type: "suburb", region: "North Yorkshire" },
  { slug: "dunnington", lat: 53.920, lng: -1.099, postcode: "YO19", type: "village", region: "North Yorkshire" },
  { slug: "wheldrake", lat: 53.920, lng: -1.099, postcode: "YO19", type: "village", region: "North Yorkshire" },
  { slug: "escrick", lat: 53.920, lng: -1.099, postcode: "YO19", type: "village", region: "North Yorkshire" },
  { slug: "deighton", lat: 53.920, lng: -1.099, postcode: "YO19", type: "village", region: "North Yorkshire" },
  { slug: "askham-bryan", lat: 53.920, lng: -1.099, postcode: "YO23", type: "village", region: "North Yorkshire" },
  { slug: "askham-richard", lat: 53.920, lng: -1.099, postcode: "YO23", type: "village", region: "North Yorkshire" },
  { slug: "rufforth", lat: 53.920, lng: -1.099, postcode: "YO23", type: "village", region: "North Yorkshire" },
  { slug: "acomb", lat: 53.959, lng: -1.082, postcode: "YO24", type: "suburb", region: "North Yorkshire" },
  { slug: "fulford", lat: 53.959, lng: -1.082, postcode: "YO10", type: "suburb", region: "North Yorkshire" },
  { slug: "heslington", lat: 53.959, lng: -1.082, postcode: "YO10", type: "suburb", region: "North Yorkshire" },
  { slug: "stockton-on-the-forest", lat: 53.990, lng: -1.072, postcode: "YO32", type: "village", region: "North Yorkshire" },
  { slug: "holtby", lat: 53.990, lng: -1.072, postcode: "YO19", type: "village", region: "North Yorkshire" },
  { slug: "osbaldwick", lat: 53.990, lng: -1.072, postcode: "YO10", type: "suburb", region: "North Yorkshire" },
  { slug: "heworth", lat: 53.990, lng: -1.072, postcode: "YO31", type: "suburb", region: "North Yorkshire" },
  { slug: "tang-hall", lat: 53.959, lng: -1.082, postcode: "YO31", type: "suburb", region: "North Yorkshire" },
  { slug: "yorkshire", lat: 53.957, lng: -1.082, postcode: "YO", type: "region", region: "Yorkshire" },
];

export const NEARBY_LOCATIONS: Record<string, string[]> = {
  default: [
    "york",
    "harrogate",
    "wetherby",
    "leeds",
    "yorkshire",
  ],
  leeds: [
    "harrogate",
    "knaresborough",
    "garforth",
    "rothwell",
    "horsforth",
    "otley",
    "wetherby",
    "york",
  ],
  york: [
    "selby",
    "tadcaster",
    "pocklington",
    "elvington",
    "welburn",
    "stamford-bridge",
    "towton",
    "wetherby",
    "harrogate",
    "leeds",
  ],
  selby: [
    "york",
    "tadcaster",
    "cawood",
    "riccall",
    "pocklington",
    "elvington",
    "welburn",
    "stamford-bridge",
  ],
  tadcaster: [
    "york",
    "selby",
    "wetherby",
    "leeds",
    "sherburn-in-elmet",
    "cawood",
    "riccall",
  ],
  pocklington: [
    "york",
    "selby",
    "elvington",
    "welburn",
    "stamford-bridge",
    "tadcaster",
    "cawood",
  ],
  elvington: [
    "york",
    "pocklington",
    "welburn",
    "stamford-bridge",
    "selby",
    "tadcaster",
  ],
  welburn: [
    "york",
    "elvington",
    "pocklington",
    "stamford-bridge",
    "selby",
    "tadcaster",
  ],
  "stamford-bridge": [
    "york",
    "welburn",
    "elvington",
    "pocklington",
    "selby",
    "tadcaster",
  ],
  wetherby: [
    "york",
    "leeds",
    "harrogate",
    "tadcaster",
    "sherburn-in-elmet",
    "towton",
    "knaresborough",
  ],
  towton: [
    "york",
    "wetherby",
    "leeds",
    "harrogate",
    "tadcaster",
    "knaresborough",
  ],
  harrogate: [
    "ripley",
    "knaresborough",
    "spofforth",
    "follifoot",
    "pannal",
    "beckwithshaw",
    "darely",
    "starbeck",
    "wetherby",
    "york",
  ],
  knaresborough: [
    "harrogate",
    "ripley",
    "spofforth",
    "follifoot",
    "pannal",
    "beckwithshaw",
    "darely",
    "starbeck",
    "wetherby",
    "york",
  ],
  ripley: [
    "harrogate",
    "knaresborough",
    "spofforth",
    "follifoot",
    "pannal",
    "beckwithshaw",
    "darely",
    "starbeck",
    "york",
  ],
  spofforth: [
    "harrogate",
    "knaresborough",
    "ripley",
    "follifoot",
    "pannal",
    "beckwithshaw",
    "darely",
    "starbeck",
    "wetherby",
    "york",
  ],
  follifoot: [
    "harrogate",
    "knaresborough",
    "ripley",
    "spofforth",
    "pannal",
    "beckwithshaw",
    "darely",
    "starbeck",
    "wetherby",
    "york",
  ],
  pannal: [
    "harrogate",
    "knaresborough",
    "ripley",
    "spofforth",
    "follifoot",
    "beckwithshaw",
    "darely",
    "starbeck",
    "york",
  ],
  beckwithshaw: [
    "harrogate",
    "knaresborough",
    "ripley",
    "spofforth",
    "follifoot",
    "pannal",
    "darely",
    "starbeck",
    "york",
  ],
  darely: [
    "harrogate",
    "knaresborough",
    "ripley",
    "spofforth",
    "follifoot",
    "pannal",
    "beckwithshaw",
    "starbeck",
    "york",
  ],
  starbeck: [
    "harrogate",
    "knaresborough",
    "ripley",
    "spofforth",
    "follifoot",
    "pannal",
    "beckwithshaw",
    "darely",
    "york",
  ],
  ripon: [
    "thirsk",
    "masham",
    "boroughbridge",
    "york",
    "harrogate",
    "easingwold",
    "helmsley",
    "pickering",
  ],
  thirsk: [
    "ripon",
    "masham",
    "boroughbridge",
    "easingwold",
    "helmsley",
    "pickering",
    "york",
    "harrogate",
  ],
  masham: [
    "ripon",
    "thirsk",
    "boroughbridge",
    "easingwold",
    "helmsley",
    "pickering",
    "york",
    "harrogate",
  ],
  boroughbridge: [
    "ripon",
    "thirsk",
    "masham",
    "easingwold",
    "helmsley",
    "pickering",
    "york",
    "harrogate",
  ],
  easingwold: [
    "york",
    "ripon",
    "harrogate",
    "helmsley",
    "pickering",
    "thirsk",
    "masham",
    "boroughbridge",
  ],
  helmsley: [
    "york",
    "ripon",
    "easingwold",
    "pickering",
    "thirsk",
    "masham",
    "boroughbridge",
    "harrogate",
  ],
  pickering: [
    "york",
    "ripon",
    "easingwold",
    "helmsley",
    "thirsk",
    "masham",
    "boroughbridge",
    "harrogate",
  ],
  "sherburn-in-elmet": [
    "leeds",
    "tadcaster",
    "wetherby",
    "york",
    "garforth",
    "rothwell",
    "towton",
  ],
  cawood: [
    "selby",
    "york",
    "riccall",
    "tadcaster",
    "pocklington",
    "elvington",
    "welburn",
    "stamford-bridge",
  ],
  riccall: [
    "selby",
    "cawood",
    "york",
    "tadcaster",
    "pocklington",
    "elvington",
    "welburn",
    "stamford-bridge",
  ],
  bishopthorpe: [
    "york",
    "copmanthorpe",
    "acomb",
    "fulford",
    "heslington",
    "dunnington",
    "wheldrake",
    "escrick",
  ],
  copmanthorpe: [
    "york",
    "bishopthorpe",
    "askham-bryan",
    "askham-richard",
    "rufforth",
    "acomb",
    "fulford",
  ],
  haxby: [
    "york",
    "strensall",
    "huntington",
    "stockton-on-the-forest",
    "holtby",
    "osbaldwick",
    "heworth",
    "tang-hall",
  ],
  strensall: [
    "york",
    "haxby",
    "huntington",
    "stockton-on-the-forest",
    "holtby",
    "osbaldwick",
    "heworth",
  ],
  huntington: [
    "york",
    "haxby",
    "strensall",
    "stockton-on-the-forest",
    "holtby",
    "osbaldwick",
    "heworth",
    "tang-hall",
  ],
  dunnington: [
    "york",
    "wheldrake",
    "escrick",
    "deighton",
    "bishopthorpe",
    "copmanthorpe",
    "acomb",
  ],
  wheldrake: [
    "york",
    "dunnington",
    "escrick",
    "deighton",
    "elvington",
    "pocklington",
    "bishopthorpe",
  ],
  escrick: [
    "york",
    "wheldrake",
    "dunnington",
    "deighton",
    "bishopthorpe",
    "copmanthorpe",
    "acomb",
  ],
  deighton: [
    "york",
    "escrick",
    "wheldrake",
    "dunnington",
    "bishopthorpe",
    "copmanthorpe",
    "acomb",
  ],
  "askham-bryan": [
    "york",
    "copmanthorpe",
    "askham-richard",
    "rufforth",
    "acomb",
    "fulford",
    "bishopthorpe",
  ],
  "askham-richard": [
    "york",
    "askham-bryan",
    "copmanthorpe",
    "rufforth",
    "acomb",
    "fulford",
    "bishopthorpe",
  ],
  rufforth: [
    "york",
    "askham-bryan",
    "askham-richard",
    "copmanthorpe",
    "acomb",
    "fulford",
    "bishopthorpe",
  ],
  acomb: [
    "york",
    "bishopthorpe",
    "copmanthorpe",
    "askham-bryan",
    "askham-richard",
    "rufforth",
    "fulford",
    "heslington",
  ],
  fulford: [
    "york",
    "bishopthorpe",
    "copmanthorpe",
    "acomb",
    "heslington",
    "askham-bryan",
    "askham-richard",
    "rufforth",
  ],
  heslington: [
    "york",
    "acomb",
    "fulford",
    "bishopthorpe",
    "copmanthorpe",
    "askham-bryan",
    "askham-richard",
    "rufforth",
  ],
  "stockton-on-the-forest": [
    "york",
    "haxby",
    "strensall",
    "huntington",
    "holtby",
    "osbaldwick",
    "heworth",
    "tang-hall",
  ],
  holtby: [
    "york",
    "haxby",
    "strensall",
    "huntington",
    "stockton-on-the-forest",
    "osbaldwick",
    "heworth",
    "tang-hall",
  ],
  osbaldwick: [
    "york",
    "haxby",
    "strensall",
    "huntington",
    "stockton-on-the-forest",
    "holtby",
    "heworth",
    "tang-hall",
  ],
  heworth: [
    "york",
    "haxby",
    "strensall",
    "huntington",
    "stockton-on-the-forest",
    "holtby",
    "osbaldwick",
    "tang-hall",
  ],
  "tang-hall": [
    "york",
    "haxby",
    "strensall",
    "huntington",
    "stockton-on-the-forest",
    "holtby",
    "osbaldwick",
    "heworth",
  ],
  garforth: [
    "leeds",
    "rothwell",
    "sherburn-in-elmet",
    "tadcaster",
    "wetherby",
    "york",
    "horsforth",
  ],
  rothwell: [
    "leeds",
    "garforth",
    "sherburn-in-elmet",
    "tadcaster",
    "wetherby",
    "york",
    "horsforth",
  ],
  horsforth: [
    "leeds",
    "otley",
    "garforth",
    "rothwell",
    "wetherby",
    "york",
    "harrogate",
  ],
  otley: [
    "leeds",
    "horsforth",
    "harrogate",
    "wetherby",
    "york",
    "knaresborough",
    "ripley",
  ],
};

const EARTH_RADIUS_MILES = 3958.8;

function toRadians(degrees: number): number {
  return degrees * (Math.PI / 180);
}

function haversineDistance(
  lat1: number,
  lng1: number,
  lat2: number,
  lng2: number
): number {
  const dLat = toRadians(lat2 - lat1);
  const dLng = toRadians(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRadians(lat1)) *
      Math.cos(toRadians(lat2)) *
      Math.sin(dLng / 2) ** 2;

  return EARTH_RADIUS_MILES * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

export function getLocationsWithinRadius(
  centerLat: number,
  centerLng: number,
  radiusMiles: number
): string[] {
  return LOCATIONS.filter(({ lat, lng }) => {
    const distance = haversineDistance(centerLat, centerLng, lat, lng);
    return distance <= radiusMiles;
  }).map(({ slug }) => slug);
}
